# Generated by Django 5.1 on 2025-07-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
        migrations.AddField(
            model_name='shipping',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-22 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(default='Default State', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='zip_code',
            field=models.CharField(default='Default Zip Code', max_length=20),
        ),
    ]
